### PR TITLE
Radar chart (new chart type)

### PR DESCRIPTION
**Pull request by denisinvader**
**Related issue**
#2

**Example screenshot**
radar chart examples

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#2: [new chart type]: radar chart](https://issuehunt.io/repos/200573908/issues/2)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by timqian** [comment]
Thanks, @denisinvader , I will review this PR ASAP

It will be great if you can add some screenshots of the new chart; run `npm run lint` and fix the linting issues

This is the first chart type of PR, I have not set up PR requirements, sorry about that

**Comment by denisinvader** [comment]
I have already run `npm run lint` and fixed all errors in `src/Radar.js`, but there are still some errors in other files.

radar chart example

I can provide more explanation about component options and more screenshots later. There are still some issues with labels positioning (on big-sized charts).

Does semi-opacity fit the style of the library?

**Comment by timqian** [comment]
@denisinvader Thanks! The semi-opacity style looks great, is the PR ready for review?

**Comment by denisinvader** [comment]
@timqian yes, everything is ready

**Comment by timqian** [comment]
LGTM

**Pull request merged**
