### PR TITLE
Add a new StackedBar chart

### PR DESCRIPTION
**Pull request by matt3play**
This change adds a separate StackedBar type of chart.  

I did consider modifying the main Bar chart to just take multiple data arrays as input, but decided that it was better create a separate chart type, as it seems likely that you might want to have some sort of "side-by-side" bar chart in the future.

I also updated the example for the bar chart so that the title and axes made sense.

**Screenshot before and after this change**

image

### CODE REVIEW

**Comment by timqian** [comment]
@matt3play Firstly, thanks for your work!

For stacked bar chart, I am thinking, it might be better if legend and color are also added as how the pie chart behaves.

Because if no legend is provided, the stacked bar might look a little confusing before the mouse hovers on the bars

**Comment by matt3play** [comment]
Good point!

I've got a PR up with tooltips, but adding a legend makes sense too.  Maybe
as an optional add-on

**Comment by matt3play** [comment]
Add a legend, and changed the chart to always be colored (instead of just coloring on mouseover).  Now it looks like this:

image

**Comment by matt3play** [comment]
Also for clarity, here's a screenshot with the mouse over a bar to show that label:

image

**Comment by timqian** [comment]
Looks great! Will play with it a bit, add some doc and then push to npm soon. Thanks for your work!

**Comment by timqian** [comment]
I did some updates https://github.com/timqian/chart.xkcd/commit/abe5d809506612d74e2afab2c3a9d4f27464788e and have published this new chart type to [npm](https://www.npmjs.com/package/chart.xkcd) and [website](https://timqian.com/chart.xkcd/#stacked_bar_chart).

**Pull request merged**
